### ISSUE TITLE
Install instruction not clear

### ISSUE THREAD

**Issue by typicalC** [random532/brut#3]
I'd love to use xdisk , and am in fact in need of a GUI-based Free-BSD partition manager desperately... 

However, It is not at clear to me how I must install xdisk.  

Perhaps `Download ports/Makefile and ports/pkg-descr` and `Run "make makesum" and "make install clean"` is clear enough for most people, but not me. 

Are these the *only* files I must download ? If no, which else ? if yes, what does it 'make' from ?

I request you to make a _step-by-step_ install guide _or_ a _script installer_ (whichever you find easier) that makes it easy to install for folks like me ... please ?

Btw I use NomadBSD , stock.

**Comment by typicalC** [comment]
Upon running `make makesum` in the PORT directory, I get `make: "/usr/share/mk/bsd.port.mk" line 32: Cannot open /usr/ports/Mk/bsd.port.mk` , `make: Fatal errors encountered -- cannot continue`  and `make: stopped in /home/nomad/xdisk-master/PORT` ... And the exact same thing when trying `make install clean` .

**Comment by random532** [comment]
Hey, 
Downloading the ports tree should fix it.

The ports tree should contain the files needed to build ports. Xdisk behaves just like any other port, except that you need to additionally run "make makesum".

https://www.freebsd.org/doc/handbook/ports-using.html

**Comment by typicalC** [comment]
Thanks , random532 . I need a GUI partition manager badly, and as you can guess from me using NomadBSD, I'm very new to this  BSD business :) 
Thanks for linking the official documentation, I hear its pretty good.
BTW, do i 'download' the ports tree or 'install' it ? SInce I'm having a lot of issues configuring wifi drivers with my BSD system, I hope i dont need to 'download' 0_0 ...

**Comment by random532** [comment]
This should be possible.
Download the source files in the top directory (without those folders, especially not /ports/Makefile). Then compile with this command: make LOCALBASE=/usr/local

I will add a tarball in the future. Might add a compiled binary as well.
